import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const plusJakartaSans = localFont({
    src: "./fonts/PlusJakartaSans-VariableFont_wght.ttf",
    variable: "--font-plus-jakarta-sans",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Mortgage Repayment Calculator",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${plusJakartaSans.variable} lg:bg-slate-100  antialiased`}>
                <main className="lg:px-6">{children}</main>
                <footer className="text-white bg-slate-900 text-sm p-6 text-center">
                    <p>
                        Challenge by{" "}
                        <a
                            href="https://www.frontendmentor.io?ref=challenge"
                            className="text-lime underline hover:no-underline focus-visible:no-underline"
                        >
                            Frontend Mentor
                        </a>
                        . Coded by{" "}
                        <a
                            href="https://rafaeldevvv.github.io/portfolio"
                            className="text-lime underline hover:no-underline focus-visible:no-underline"
                        >
                            Rafael Maia
                        </a>
                        .
                    </p>
                </footer>
            </body>
        </html>
    );
}
